from __future__ import annotations

from rbccps_od.config.schemas import ModelAssetSpec


DEFAULT_MODEL_REGISTRY: dict[str, ModelAssetSpec] = {
    "yolov26_base": ModelAssetSpec(
        name="yolov26_base",
        version="local-repo",
        filename="yolo26m.pt",
        url=None,
        checksum=None,
        local_path="datasets/yolov26_weights/yolo26m.pt",
        required=True,
        license_name="repo-local",
        description="Base YOLOv26 weights for the current streetlight detector baseline.",
    ),
    "lowlight_enhancer": ModelAssetSpec(
        name="lowlight_enhancer",
        version="master",
        filename="Zero-DCE-master.zip",
        url="https://github.com/Li-Chongyi/Zero-DCE/archive/refs/heads/master.zip",
        implementation="source_archive_only",
        source_repo_url="https://github.com/Li-Chongyi/Zero-DCE",
        paper_url="https://openaccess.thecvf.com/content_CVPR_2020/papers/Guo_Zero-Reference_Deep_Curve_Estimation_for_Low-Light_Image_Enhancement_CVPR_2020_paper.pdf",
        license_name="CC BY-NC 4.0",
        description="Exact upstream Zero-DCE source bundle for low-light enhancement integration.",
        metadata={
            "checkpoint_hint": "Zero-DCE_code/snapshots/Epoch99.pth",
            "runtime_status": "source_archive_cached",
        },
    ),
    "zero_dce_epoch99": ModelAssetSpec(
        name="zero_dce_epoch99",
        version="master",
        filename="Epoch99.pth",
        url=None,
        implementation="archive_member",
        source_repo_url="https://github.com/Li-Chongyi/Zero-DCE",
        paper_url="https://openaccess.thecvf.com/content_CVPR_2020/papers/Guo_Zero-Reference_Deep_Curve_Estimation_for_Low-Light_Image_Enhancement_CVPR_2020_paper.pdf",
        license_name="CC BY-NC 4.0",
        description="Pinned Zero-DCE checkpoint extracted from the official upstream source archive.",
        metadata={
            "archive_asset": "lowlight_enhancer",
            "archive_member": "Zero-DCE-master/Zero-DCE_code/snapshots/Epoch99.pth",
            "runtime_status": "ready_from_cached_archive",
        },
    ),
    "retinex_decomposition": ModelAssetSpec(
        name="retinex_decomposition",
        version="main",
        filename="RetinexNet_Pytorch-main.zip",
        url="https://github.com/langmanbusi/RetinexNet_Pytorch/archive/refs/heads/main.zip",
        implementation="source_archive_only",
        source_repo_url="https://github.com/langmanbusi/RetinexNet_Pytorch",
        paper_url="https://arxiv.org/abs/1808.04560",
        license_name="upstream-repo-unspecified",
        description="Exact upstream RetinexNet PyTorch source bundle for decomposition-stage integration.",
        metadata={
            "checkpoint_hint": "ckpts/ in upstream repo",
            "runtime_status": "source_archive_cached",
        },
    ),
    "retinex_decom_9200": ModelAssetSpec(
        name="retinex_decom_9200",
        version="main",
        filename="9200.tar",
        url=None,
        implementation="archive_member",
        source_repo_url="https://github.com/langmanbusi/RetinexNet_Pytorch",
        paper_url="https://arxiv.org/abs/1808.04560",
        license_name="upstream-repo-unspecified",
        description="Pinned RetinexNet decomposition checkpoint extracted from the official upstream source archive.",
        metadata={
            "archive_asset": "retinex_decomposition",
            "archive_member": "RetinexNet_Pytorch-main/ckpts/ReNet_LOL/Decom/9200.tar",
            "runtime_status": "ready_from_cached_archive",
        },
    ),
    "retinex_relight_9200": ModelAssetSpec(
        name="retinex_relight_9200",
        version="main",
        filename="9200.tar",
        url=None,
        implementation="archive_member",
        source_repo_url="https://github.com/langmanbusi/RetinexNet_Pytorch",
        paper_url="https://arxiv.org/abs/1808.04560",
        license_name="upstream-repo-unspecified",
        description="Pinned RetinexNet relight checkpoint extracted from the official upstream source archive.",
        metadata={
            "archive_asset": "retinex_decomposition",
            "archive_member": "RetinexNet_Pytorch-main/ckpts/ReNet_LOL/Relight/9200.tar",
            "runtime_status": "ready_from_cached_archive",
        },
    ),
    "domain_adaptation": ModelAssetSpec(
        name="domain_adaptation",
        version="main",
        filename="DAI-Net-main.zip",
        url="https://github.com/ZPDu/DAI-Net/archive/refs/heads/main.zip",
        implementation="source_archive_only",
        source_repo_url="https://github.com/ZPDu/DAI-Net",
        paper_url="https://arxiv.org/abs/2312.01220",
        license_name="upstream-repo-unspecified",
        description="Exact upstream DAI-Net source bundle for day-night domain adaptation integration.",
        metadata={
            "weight_hints": [
                "README references decomp.pth",
                "README references vgg16_reducedfc.pth",
                "README references DarkFaceZSDA and DarkFaceFS checkpoints",
            ],
            "runtime_status": "code_cached_weights_external",
            "streetlight_runtime_policy": "pinned_but_disabled_by_default",
        },
    ),
    "tracker_bundle": ModelAssetSpec(
        name="tracker_bundle",
        version="main",
        filename="ByteTrack-main.zip",
        url="https://github.com/FoundationVision/ByteTrack/archive/refs/heads/main.zip",
        implementation="source_archive_only",
        source_repo_url="https://github.com/FoundationVision/ByteTrack",
        paper_url="https://arxiv.org/abs/2110.06864",
        license_name="MIT",
        description="DEPRECATED: Exact upstream ByteTrack source bundle. To be replaced with UCMC.",
        metadata={
            "runtime_status": "algorithm_source_pinned",
            "integration_mode": "consume detector outputs from YOLOv26 instead of ByteTrack detector checkpoints",
        },
    ),
}
